services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio_aiqfome_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
    depends_on:
      - db
    command: bash -c "composer install && cp .env.exemple .env &&php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: postgres:15
    container_name: desafio_aiqfome_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  vendor_data:
